name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build Swift Package
        run: xcodebuild build -workspace .swiftpm/xcode/package.xcworkspace -scheme PagingView -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO

      - name: Test Swift Package
        run: xcodebuild test -workspace .swiftpm/xcode/package.xcworkspace -scheme PagingView -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16 Pro' CODE_SIGNING_ALLOWED=NO

      - name: Build Demo
        run: xcodebuild build -project PagingView.xcodeproj -scheme UIKitExample -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO
