name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build PagingView
        run: xcodebuild build -project PagingView.xcodeproj -scheme PagingView -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO

      - name: Build SwiftUIExample
        run: xcodebuild build -project PagingView.xcodeproj -scheme SwiftUIExample -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO

      - name: Build UIKitExample
        run: xcodebuild build -project PagingView.xcodeproj -scheme UIKitExample -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO
